### ISSUE TITLE
Add re-usable job hooks to notify Slack on status of job 

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-pipeline-tasks#2]
When a pipeline runs a job, the CI `on` hooks provides a method for alerting Slack on the status of the job. To standardize and minimize our pipelines, create reusable hooks that can notify slack on a job's success, failure, error, and abort.

## Acceptance Criteria

- [x] Creates hooks to easily add `on_error`, `on_success`, `on_failure`, and `on_abort`.
- [x] Hooks can use the pipeline related environment variables to make them more reusable.

**Comment by drewbo** [comment]
Closed via https://github.com/cloud-gov/pages-pipeline-tasks/commit/c0421b23599e4907698d26eaee57faf87b241d38
